### ISSUE TITLE
Method not allowed

### ISSUE THREAD

**Issue by apoorvopen** [SthPhoenix/InsightFace-REST#1]
When I try to call the API using postman, I am getting this error.

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>`

Please let me know what can be done. I am using converted base64 images and adding in JSON requests like "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQA.........."

**Comment by SthPhoenix** [comment]
Hi! Are you sending request to `http://localhost:6000/extract`?

Also there seems to be mistake in my code: I was using default port other than 6000, declared in `deploy.sh`. 
You can either pull repo again, or add environment variable `-e PORT=6000` to `docker run` statement in `deploy.sh`

**Comment by apoorvopen** [comment]
Thanks for responding, I am trying to implement it using app.py. Can you please tell me what will happen in that case? 

Will it work now, as the flask server is being started on http://0.0.0.0:18080/ previously. Do let me know how I can use that.

**Comment by SthPhoenix** [comment]
`Method not allowed` is caused by sending request to endpoint not supporting it.
You might get it if you are trying to send data to [localhost:18080](http://localhost:18080) instead of [localhost:18080/extract](http://localhost:18080/extract)

I have updated documentation, hope it's more clear now. Also added support for base64 generated on browser side, i.e. containing `data:image/jpeg;base64,`.

P.S. Returned port 18080 back, since port 6000 seems to be blocked by Firefox while debugging as the one used for X Window System.
