### ISSUE TITLE
About retinaface dynamic input size

### ISSUE THREAD

**Issue by Talgin** [SthPhoenix/InsightFace-REST#12]
Hi @SthPhoenix,
Thank you for this repo, I've finally got proper conversion (tried with original mxnet to onnx converter and different other methods from github) with good performance. But one question regarding the conversion of original Retinaface model is how to set dynamic input size like in their example? I mean, the original model accepts different sizes and gives proper output, but the converted model receives only 640x640 and I have some not found faces. E.g. 2560x1440 pixel frame and model could not find faces of approx. 60x35 size and couldn't find some slightly turned faces (the original model finds them ok). What can I do to convert the model to be saved with dynamic input size?

**Comment by SthPhoenix** [comment]
Hi! For now dynamic input shapes are not supported, you can try changing max image size during conversion to fit you needs.

**Comment by Talgin** [comment]
Hi @SthPhoenix ,
Thank you for your advice, I've changed the input and set the scales according to max_size as you suggested. Everything works fine, except the batching. Is it possible to do batching with different input shapes of images? (if I'm not mistaken we cannot create a batch with images of different dimensions, e.g. (900, 675, 3), (506, 900, 3), (600, 900, 3)).

**Comment by SthPhoenix** [comment]
> Hi @SthPhoenix ,
> Thank you for your advice, I've changed the input and set the scales according to max_size as you suggested. Everything works fine, except the batching. Is it possible to do batching with different input shapes of images? (if I'm not mistaken we cannot create a batch with images of different dimensions, e.g. (900, 675, 3), (506, 900, 3), (600, 900, 3)).

Batching is not fully implemented in this repo right now, conversion scripts support it, but inference script still need to be updated. 

And yes, you should resize/pad images to same size for batching. You can check [imagedata.py](https://github.com/SthPhoenix/InsightFace-REST/blob/master/src/api_trt/modules/imagedata.py) as example. Since postprocessing code of Retinaface doesn't support batching, it's optimal to implement batching for face recognition, which requires fixed 112x112 face crops.

**Comment by SthPhoenix** [comment]
Closing for now, since batch inference of ArcFace model was added in previous commits.
