### ISSUE TITLE
why insightFace-Rest only get fewer faces when deploying on trt with default parameters compared with the result showing on readme?

### ISSUE THREAD

**Issue by Asher-1** [SthPhoenix/InsightFace-REST#25]
![微信图片_20210312084629](https://user-images.githubusercontent.com/16451440/110874849-7411be00-830f-11eb-98fa-a1ddce99bbd7.png)

**Comment by SthPhoenix** [comment]
I was waiting for this question ) My mistake, I was testing different settings restarting server, but not reloading docs page.
I have noticed this few days ago and spent a lot of time figuring out why I got fewer faces with same settings as in readme, but it seems that I have just taken screenshot when max image size was set to 1024x1024, instead of 640x640 as you can see on the screenshot.

**Comment by Asher-1** [comment]
got it,  thanks for your work

**Comment by SthPhoenix** [comment]
Closing for now, I'll update image to actual results in few days.
